### ISSUE TITLE
对于逻辑运算符与||的处理

### ISSUE THREAD

**Issue by guilipan** [aui/tmodjs#48]
简洁语法中,对于逻辑运算符与||会被解析成管道标记而当成辅助方法,如

{{ hasClass || hasData ? 'abc' :'def' }} 

tmod编译的时候会报错

**Comment by jacobking** [comment]
template.js和debug版里面的version还是3.0.0？不是3.0.3了吗

**Comment by DavidKk** [comment]
bower 上面也没更新到 3.0.3 都是3.0.0的 而且dist 里面也是3.0.0 {{ a || c }} 一样报错

**Comment by anglezhang** [comment]
一、按文件与目录组织模板

template('tpl/home/main', data),如何使用按文件目录组织模版?

**Comment by Metoyo** [comment]
@anglezhang 我用其他方法实现了“按文件与目录组织模板”。
```
function renderTpl(file, data, container){
        $.ajax({
            async:false,
            url : file,
            success : function(result){
                var render = template.compile(result);
                var html = render(data);
                $(container).html(html);
            }
        });
    }
```
`renderTpl('/weixin/teacher/tpl.html', {xuexiao: '太安厅演示', xingming: 'ganludeyun'}, '#topBar');`

**Comment by DavidKk** [comment]
@Metoyo 如果里面遇到内联 nest 或外链 include 的情况可能解决不到
