### ISSUE TITLE
编译模板出错

### ISSUE THREAD

**Issue by daddybh** [aui/tmodjs#78]
hi，我在使用tmodjs编译模板，出现以下错误
```
 { message: 'Unexpected token: punc ())',
```
调试发现代码
https://github.com/aui/artTemplate/blob/master/src/compile.js#L231

返回一个Function，当在tmodjs 的AOTemplate.js文件中https://github.com/aui/tmodjs/blob/master/src/AOTcompile.js#L163

调用 toString()时，会在参数插入换行符和注释
```
new Function("$data", "$filename", code);
```
输出
```
"function anonymous($data,$filename
/**/) {
alert('hihi')
}"
```

目前只有我的机器会，同事电脑没问题，试过降低nodejs版本，问题还是没能解决。
请问是哪里影响到toString()的输出？本机是win8.1 64位

目前我在https://github.com/aui/tmodjs/blob/master/src/AOTcompile.js#L163
添加`.replace(/\n\/\*\*\//,"")` 删掉换行和注释符

**Comment by aui** [comment]
注释是调用 new Function 生成的，貌似只有 v8 引擎会——但是这里不应是语法错误的原因啊

**Comment by daddybh** [comment]
@aui  主要是tmodjs的_removeMetadata函数（https://github.com/aui/tmodjs/blob/master/src/tmod.js#L643）正则表达式，会连同后面函数名部分一起替换掉。

**Comment by xuhuan** [comment]
同样出错，还没有解决？

**Comment by daddybh** [comment]
@xuhuan 可以先把_removeMetadata 函数的正则改成`^\/\*TMODJS\:(?:.*)\*\/`
我已经提交pull request

**Comment by aui** [comment]
感谢，已经合并

**Comment by xuhuan** [comment]
@daddybh 感谢。
@aui 新版跑了下目前没发现问题了。
