### ISSUE TITLE
template.js 里边的中文乱码

### ISSUE THREAD

**Issue by szyjava** [aui/tmodjs#90]
配置参数：
"tmodjs-config": {
    "source":"./tpl",
    "output": "./build",
    "charset": "utf-8",
    "syntax": "simple",
    "helpers": null,
    "escape": true,
    "compress": true,
    "type": "default",
    "runtime": "template.js",
    "combo": true,
    "minify": true,
    "cache": false
  }

template.js 和 .cache下的文件  里边的中文都是乱码

**Comment by aui** [comment]
仅支持  utf8 的文件
